### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by aymanbagabas** [microsoft/go-winmd#30]
Would love to see some progress here getting the `win32` bindings for Go

**Comment by karianna** [comment]
Please see https://github.com/golang/go/issues/43838#issuecomment-1719978124

**Comment by aymanbagabas** [comment]
@karianna Could you provide any updates on the state of this project? I see a bunch of important issues, and last commit was 2 years ago.

cc/ @qmuntal @dagood

**Comment by aymanbagabas** [comment]
> We still aim to follow through on the plan laid out at [golang/go#43838 (comment)](https://github.com/golang/go/issues/43838#issuecomment-1719978124), but unfortunately we haven't been able to get to it and don't have a timeframe in mind.

It would be nice for go-winmd to get back to development to unblock things like https://github.com/saltosystems/winrt-go/issues/106, implement generics, and get winrt-go to a place where it can be fully utilized just like Rust and others WinRT implementations.
